name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "lekimnersi" --password-stdin
        docker image build -t lekimnersi/helebisrduk:latest  .
        docker push lekimnersi/helebisrduk:latest
